# trimmed to only include directories with Shopify-local patches
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/cmd/configschema"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/exporter/prometheusexporter"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/internal/coreinternal"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/processor/probabilisticsamplerprocessor"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/processor/spanmetricsprocessor"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/testbed"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"

